<?xml version="1.0" ?>
<robot name="custom_diff_robot" xmlns:xacro="http://ros.org/wiki/xacro">

    <!-- Constants-->
    <xacro:property name="pi_const" value="3.14159265"/>

    <!-- Material density-->
    <xacro:property name="density" value="2710"/>

    <!-- Body dimensions-->
    <xacro:property name="body_x_dim" value="0.4"/>
    <xacro:property name="body_y_dim" value="0.4"/>
    <xacro:property name="body_z_dim" value="0.2"/>
    <xacro:property name="body_mass" value="${density*body_x_dim*body_y_dim*body_z_dim}"/>

    <!-- Wheel dimensions-->
    <xacro:property name="wheel_radius" value="0.15"/>
    <xacro:property name="wheel_width" value="0.1"/>
    <xacro:property name="wheel_z_location" value="-0.1"/>
    <xacro:property name="wheel_mass" value="${density*pi_const*wheel_radius*wheel_radius*wheel_width}"/>
    <xacro:property name="Iz_wheel" value="${0.5*wheel_mass*wheel_radius*wheel_radius}"/>
    <xacro:property name="I_wheel" value="${-(1.0/12.0)*wheel_mass*(3.0*wheel_radius*wheel_radius+wheel_width*wheel_width)}"/>
    <xacro:macro name="inertia_wheel">
        <inertial>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <mass value="${wheel_mass}"/>
            <inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" iyy="${I_wheel}" iyz="0" izz="${Iz_wheel}" />
        </inertial>
    </xacro:macro>

    

    <!-- Controller-->
    <xacro:include filename="$(find custom_diff_robot)/urdf/robot.gazebo"/>

    <!-- Robot link and joints definition-->

    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${-wheel_z_location+wheel_radius}" rpy="0 0 0"/>
    </joint>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${body_x_dim} ${body_y_dim} ${body_z_dim}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="${body_x_dim} ${body_y_dim} ${body_z_dim}" />
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="${body_mass}"/>
            <inertia 
                    ixx="${(1/12)*body_mass*(body_y_dim*body_y_dim+body_z_dim*body_z_dim)}" 
                    ixy="0" ixz="0"
                    iyy="${(1/12)*body_mass*(body_x_dim*body_x_dim+body_z_dim*body_z_dim)}" 
                    iyz="0"
                    izz="${(1/12)*body_mass*(body_x_dim*body_x_dim+body_y_dim*body_y_dim)}"  />
        </inertial>
    </link>

    <joint name="wheel_right_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_right_link"/>
        <origin xyz="${body_x_dim/2-wheel_radius} ${-body_y_dim/2-1.2*wheel_width/2} ${wheel_z_location}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="wheel_right_link">
        <visual>
            <origin xyz="0 0 0" rpy="${pi_const/2} 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="${pi_const/2} 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}" />
            </geometry>
        </collision>

        <xacro:inertia_wheel />
    </link>

    <joint name="wheel_left_joint" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_left_link"/>
        <origin xyz="${body_x_dim/2-wheel_radius} ${body_y_dim/2+1.2*wheel_width/2} ${wheel_z_location}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <link name="wheel_left_link">
        <visual>
            <origin xyz="0 0 0" rpy="${pi_const/2} 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="0 0 0" rpy="${pi_const/2} 0 0"/>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}" />
            </geometry>
        </collision>

        <xacro:inertia_wheel />
    </link>


  <joint name="caster_back_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_link"/>
    <origin xyz="${-body_x_dim/2-1.1*wheel_radius} 0 ${wheel_z_location}" rpy="0 0 0"/>
  </joint>

  <link name="caster_back_link">
    <visual>
        <origin xyz="0 0 0" rpy="${pi_const/2} 0 0"/>
        <geometry>
            <cylinder length="${wheel_width}" radius="${wheel_radius}" />
        </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="${pi_const/2} 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}" />
      </geometry>
    </collision>

    <xacro:inertia_wheel />
  </link>

  <joint name="front_laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="front_laser_link"/>
    <origin xyz="${0.025+body_x_dim/2} 0 ${body_z_dim/2}" rpy="0 0 0"/>
  </joint>

  <link name="front_laser_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="back_laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link="back_laser_link"/>
    <origin xyz="${-body_x_dim/2-0.025} 0 ${body_z_dim/2}" rpy="0 0 ${pi_const}"/>
  </joint>

  <link name="back_laser_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>
  

  <!--<joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="-0.032 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.032 0 0.172" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>-->

</robot>
